on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                # We test around several versions that changed the names of the
                # release asset names:
                # * 1.0.30 changed the names for macos
                # * 1.0.35 changed the names for linux
                # * 1.0.39 standardized the names
                wabt-version: ["1.0.20", "1.0.29", "1.0.30", "1.0.31", "1.0.34", "1.0.35", "1.0.39"]
                os: [ubuntu-latest, macos-15-intel, windows-latest]
                include:
                    - os: ubuntu-24.04-arm
                      wabt-version: "1.0.39"
                    - os: macos-15
                      wabt-version: "1.0.39"
                exclude:
                    - os: macos-15-intel
                      wabt-version: "1.0.39"

        steps:

        - uses: actions/checkout@v6

        - name: Use wabt ${{ matrix.wabt-version }}
          uses: ./
          with:
              wabt-version: ${{ matrix.wabt-version }}

        - run: wat2wasm --help
